# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique<D-w>
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
  - name : a
    ip : 172.29.92.43
    port : 10010    # This is the incoming port on which MP will listen
                    # May be changed for further communication as usual
  - name : b
    ip : 172.29.92.43
    port : 10020
  - name : c
    ip : 172.29.92.43
    port : 10030
  - name : d
    ip : 172.29.92.43
    port : 10040
  - name : e
    ip : 172.29.92.43
    port : 10050
  - name : f
    ip : 172.29.92.43
    port : 10060
  - name : g
    ip : 172.29.92.43
    port : 10070

sendRules :
  - action : drop
    src : a
    dest : b
  - action : drop
    src : a
    dest : c
    kind : delay

receiveRules :
  - action : drop
    src : a
    dest : b
    kind : ddd

clockType : Vector

groups :
  - name : G1
    members :
      - a
      - b
      - c
  - name : G2
    members :
      - b
      - d
      - f
  - name : G3
    members :
      - c
      - e
      - f
  - name : G4
    members :
      - a
      - d
      - e
  - name : G5
    members :
      - b
      - e
      - g
  - name : G6
    members :
      - a
      - f
      - g
  - name : G7
    members :
      - c
      - d
      - g
