# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
  - name : a
    ip : 172.29.92.200
    port : 10010    # This is the incoming port on which MP will listen
                    # May be changed for further communication as usual
  - name : b
    ip : 172.29.92.200
    port : 10020
  - name : c
    ip : 172.29.92.200
    port : 10030
  - name : d
    ip : 172.29.92.200
    port : 10040

sendRules :
  - action : drop # Ack message number 4 from bob to alice will not be sent
    src : b
    dest : a
    kind : Ack
    seqNum : 2
  - action : dropAfter # Daphnie will stop sending Reply messages after seq#6
    kind : Reply
    src : d
    seqNum : 3

receiveRules :
  - action : delay # Everyone sees two copies of charlie's messages
    src : c # even though he only sends one