# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique<D-w>
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
  - name : a
    ip : 172.29.92.200
    port : 10010    # This is the incoming port on which MP will listen
                    # May be changed for further communication as usual
  - name : b
    ip : 172.29.92.200
    port : 10020
  - name : c
    ip : 172.29.92.200
    port : 10030
  - name : d
    ip : 172.29.92.200
    port : 10040

sendRules :
  - action : dropAfter 
    src : a
    seqNum: 4

receiveRules :
  - action : dropAfter 
    dest : c
    seqNum: 4

clockType : Vector

groups :
  - name : G1
    members :
      - a
      - b
      - c
  - name : G2
    members :
      - d
      - b
      - c
